name = "sb-slash"
account_id = "d5ccf1d783709bbdc23fc29786f38736"
workers_dev = true
main = "dist/main.js"
node_compat = true
kv_namespaces = [
  { binding = "USERS", id="1ad3c273d35c47ccb0b1178aef25bb91" }
]
compatibility_date = "2022-02-17"

[env.dev]
name = "sb-slash-dev"

[build]
command = "npm run pack"