name: Deploy to dev
on: [push, workflow_dispatch]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'mchangrh/sb-slash'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - name: Push to Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: dev
          SECRETS: VERSION
          BRANCH: BRANCH
        env:
          VERSION: ${{ github.sha }}
          BRANCH: ${{ github.ref }}